# Step 1: Use the official Node.js image as the base image
FROM node:18-alpine

RUN apk add shadow \
chromium \
nss \
freetype \
harfbuzz \
ca-certificates \
ttf-freefont


RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser \
    && mkdir -p /home/pptruser/Downloads \
    && chown -R pptruser:pptruser /home/pptruser

USER pptruser

# Step 2: Set the working directory inside the container
WORKDIR /home/pptruser/app

# Step 3: Copy the package.json and package-lock.json (if present)
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application files
COPY . .

# Step 6: Run the deploy-commands.js script to add slash commands to the server
RUN node './deploy-commands.js'

# Step 7: Define the command to run the application
CMD ["npm", "start"]
